#!/usr/bin/env node

import { readFileSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";

const root = resolve(import.meta.dirname, "..");
const registry = JSON.parse(readFileSync(resolve(root, "platform/apps.json"), "utf8"));

const blocks = registry.apps.filter((app) => app.status !== "archived" && app.web && app.nginx).map((app) => {
  const base = app.web.basePath;
  const websocket = app.capabilities.includes("realtime-sync") ? `
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "Upgrade";` : "";
  const upload = app.capabilities.includes("photo-uploads") ? "\n            client_max_body_size 55m;" : "";
  return `        # ${app.id} — generated from platform/apps.json
        location = ${base} {
            return 301 $scheme://$http_host$request_uri/;
        }

        location ${app.nginx.route} {
            proxy_pass http://${app.nginx.upstream.replace(/\/$/, "")}/;
            proxy_http_version 1.1;${websocket}${upload}
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }`;
}).join("\n\n");

const config = `# Generated by scripts/generate-nginx.mjs from platform/apps.json.
events {
    worker_connections 1024;
}

http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;
    log_format main '$remote_addr - $remote_user [$time_local] "$request" $status $body_bytes_sent "$http_referer" "$http_user_agent" "$http_x_forwarded_for"';
    access_log /var/log/nginx/access.log main;
    error_log /var/log/nginx/error.log warn;
    sendfile on;
    keepalive_timeout 65;

    server {
        listen 80;
        server_name localhost;

${blocks}
    }
}
`;

if (process.argv.includes("--write")) {
  writeFileSync(resolve(root, "infra/nginx/nginx.conf"), config);
  process.stdout.write("Updated infra/nginx/nginx.conf from the app registry.\n");
} else {
  process.stdout.write(config);
}
